apiVersion: v1
kind: Pod
metadata:
  name: pod-name-prefix-{{ POD_POSTFIX }}
  labels:
    app: web
spec:
  containers:
    - name: gocd-agent-container-{{ CONTAINER_POSTFIX }}
      image: gocd/gocd-agent-docker-dind:v19.12.0
      env:
        - name: KUBE_TOKEN
          valueFrom:
            secretKeyRef:
              name: secrets-for-gocd
              key: K8S_API_TOKEN
        - name: DOCKERHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: secrets-for-gocd
              key: DOCKERHUB_USERNAME
        - name: DOCKERHUB_ORG
          valueFrom:
            secretKeyRef:
              name: secrets-for-gocd
              key: DOCKERHUB_ORG
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      securityContext:
        privileged: true
