apiVersion: v1
kind: Secret
metadata:
  name: secrets-for-gocd
type: Opaque
data:
  K8S_API_TOKEN: BASE64-KUBERNETES-API-TOKEN-GOES-HERE
  DOCKERHUB_USERNAME: aWZhcmZhbg==
  DOCKERHUB_ORG: aWZhcmZhbm9yZw==
